apiVersion: v1
kind: Service
metadata:
  name: audio-processor
  namespace: asr-platform
spec:
  type: ClusterIP
  selector:
    app: audio-processor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
